spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petnote?useSSL=false&serverTimezone=Asia/Seoul
    username: ysi
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: 118fad53052e3d2561e881196f94ac02
              client-secret: Cwh3kgRUhJH8eFLHYAA1ablB5yBBpLoa
              redirect-uri: http://localhost:8080/login/kakaotalk
              scope: profile
              authorization-grant-type: authorization_code
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id


  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html


logging:
  level:
    org.springframework: debug
    org.springframework.web: debug


jwt:
    secret: hello.world.ee.ff
    algorithm: "HS256"
