spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html





  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petnote?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jackson:
    date-format: yyyyMMdd
    serialization:
      write-dates-as-timestamps: false

# kakao:
#   client_id: ${KAKAO_CLIENT_ID}
#   redirect_uri: http://localhost:8080/callback
#   client_secret: ${KAKAO_CLIENT_SECRET}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.petnote.dto
