spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petnote?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jackson:
    date-format: yyyyMMdd
    serialization:
      write-dates-as-timestamps: false